-- Retained-column test fixture; not a historical database schema export.
CREATE TABLE IF NOT EXISTS `accounts` (`id` TEXT NOT NULL, `displayName` TEXT NOT NULL, `normalizedName` TEXT NOT NULL, `heightCm` REAL, `birthDateEpochDay` INTEGER, `sex` TEXT, `isProfileComplete` INTEGER NOT NULL, `createdAtEpochMillis` INTEGER NOT NULL, `updatedAtEpochMillis` INTEGER NOT NULL, PRIMARY KEY(`id`));
CREATE UNIQUE INDEX IF NOT EXISTS `index_accounts_normalizedName` ON `accounts` (`normalizedName`);
CREATE TABLE IF NOT EXISTS `app_state` (`singletonId` INTEGER NOT NULL, `primaryAccountId` TEXT, `weightDeltaKg` REAL NOT NULL, PRIMARY KEY(`singletonId`), FOREIGN KEY(`primaryAccountId`) REFERENCES `accounts`(`id`) ON UPDATE NO ACTION ON DELETE SET NULL );
CREATE INDEX IF NOT EXISTS `index_app_state_primaryAccountId` ON `app_state` (`primaryAccountId`);
CREATE TABLE IF NOT EXISTS `measurements` (`id` TEXT NOT NULL, `fingerprint` TEXT NOT NULL, `measurementType` TEXT NOT NULL, `deviceAddress` TEXT NOT NULL, `measuredAtEpochMillis` INTEGER NOT NULL, `rawPayloadHex` TEXT NOT NULL, `weightKg` REAL NOT NULL, `impedanceOhm` INTEGER, `bmi` REAL, `bodyFatPercent` REAL, `bodyFatMassKg` REAL, `waterPercent` REAL, `waterMassKg` REAL, `muscleMassKg` REAL, `skeletalMuscleMassKg` REAL, `boneMassKg` REAL, `proteinPercent` REAL, `proteinMassKg` REAL, `visceralFatLevel` REAL, `basalMetabolicRateKcal` REAL, `metabolicAge` INTEGER, `leanBodyMassKg` REAL, `algorithmVersion` TEXT, `healthConnectStatus` TEXT NOT NULL, `healthConnectError` TEXT, `healthConnectWeightSynced` INTEGER NOT NULL, `createdAtEpochMillis` INTEGER NOT NULL, `accountId` TEXT NOT NULL, `externalSyncPolicy` TEXT NOT NULL, `sourcePendingId` TEXT, `deduplicationHash` TEXT, PRIMARY KEY(`id`), FOREIGN KEY(`accountId`) REFERENCES `accounts`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE );
CREATE UNIQUE INDEX IF NOT EXISTS `index_measurements_fingerprint` ON `measurements` (`fingerprint`);
CREATE INDEX IF NOT EXISTS `index_measurements_accountId_measuredAtEpochMillis` ON `measurements` (`accountId`, `measuredAtEpochMillis`);
CREATE UNIQUE INDEX IF NOT EXISTS `index_measurements_sourcePendingId` ON `measurements` (`sourcePendingId`);
CREATE UNIQUE INDEX IF NOT EXISTS `index_measurements_deduplicationHash` ON `measurements` (`deduplicationHash`);
CREATE TABLE IF NOT EXISTS `pending_measurements` (`id` TEXT NOT NULL, `deviceAddress` TEXT NOT NULL, `measuredAtEpochSecond` INTEGER NOT NULL, `measuredAtNano` INTEGER NOT NULL, `weightKg` REAL NOT NULL, `impedanceOhm` INTEGER NOT NULL, `isStable` INTEGER NOT NULL, `hasImpedance` INTEGER NOT NULL, `rawPayload` BLOB NOT NULL, `deduplicationHash` TEXT NOT NULL, `enqueuedAtEpochMillis` INTEGER NOT NULL, `rawWeight` INTEGER NOT NULL, PRIMARY KEY(`id`));
CREATE UNIQUE INDEX IF NOT EXISTS `index_pending_measurements_deduplicationHash` ON `pending_measurements` (`deduplicationHash`);
CREATE INDEX IF NOT EXISTS `index_pending_measurements_enqueuedAtEpochMillis_id` ON `pending_measurements` (`enqueuedAtEpochMillis`, `id`);
CREATE TABLE IF NOT EXISTS `measurement_tombstones` (`deduplicationHash` TEXT NOT NULL, `expiresAtEpochMillis` INTEGER NOT NULL, PRIMARY KEY(`deduplicationHash`));
